{
    'name': 'Dtech Inventory Modification',
    'version': '18.0.0.1',
    'summary': 'Dtech Inventory Modification',
    'category': 'Inventory',
    'author': 'DTech',
    'depends': ['base', 'product', 'stock', 'hr', 'mail', 'project_stock_account', 'stock_delivery',],
    'data': [
        'security/ir.model.access.csv',
        'security/stock_security.xml',
        'security/product_category_approval_security.xml',
        'reports/delivery_note.xml',
        'views/product_template_view.xml',
        'views/product_brand_view.xml',
        'data/sequence.xml',
        'data/cron.xml',
        'data/email_template.xml',
        'views/product_category_view.xml',
        'views/stock_picking_view.xml',
        'views/stock_picking_type_view.xml',
        'views/stock_quant_view.xml',
        'views/stock_return_picking_views.xml',
        'views/stock_count_notification_views.xml',
        'views/stock_count_notification_days.xml',
        'views/res_config_settings_views.xml',
        'views/product_category_reject_wizard_views.xml',
        'views/preferred_supplier_view.xml',
        'views/purchase_order_view.xml',
        'views/res_driver_views.xml',
        'views/replacement_request_views.xml',
    ],
    'license': 'LGPL-3',
    'installable': True,
    'application': False,
}
