from . import product_template
from . import product_brand
from . import product_category
from . import stock_picking
from . import stock_picking_type
from . import stock_warehouse_orderpoint
from . import stock_quant
from . import stock_move
from . import stock_count_notification
from . import stock_count_notification_days
from . import res_config_settings
from . import product_category_reject_wizard
from . import product_supplierinfo
from . import purchase_order
from . import res_driver
from . import replacement_request